name: Deploy to ECR

on:
  push:
    branches:
      - main  # This triggers the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 466670870088.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t docker-ecr-image .

      - name: Tag Docker image
        run: |
          docker tag docker-ecr-image:latest 466670870088.dkr.ecr.us-east-1.amazonaws.com/docker-ecr-project:latest

      - name: Push Docker image to ECR
        run: |
          docker push 466670870088.dkr.ecr.us-east-1.amazonaws.com/docker-ecr-project:latest

