name: Build Docker image

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Updated version

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3 # Updated version

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # - name: Log in to Amazon ECR
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     AWS_REGION: us-east-1 # Define the region
    #   run: |
    #     aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 466670870088.dkr.ecr.us-east-1.amazonaws.com

    # - name: Build Docker image
    #   run: docker build -t my-app:latest .

    # - name: Tag Docker image
    #   run: docker tag my-app:latest 466670870088.dkr.ecr.us-east-1.amazonaws.com/newuser-ecr:latest # Correct ECR repo name

    # - name: Push Docker image to ECR
    #   run: docker push 466670870088.dkr.ecr.us-east-1.amazonaws.com/newuser-ecr:latest # Correct ECR repo name

