name: ECR Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 466670870088.dkr.ecr.us-east-1.amazonaws.com

      - name: Build the Docker image
        run: |
          docker build -t docker-ecr-image .

      - name: Tag the Docker image
        run: |
          docker tag docker-ecr-image:latest 466670870088.dkr.ecr.us-east-1.amazonaws.com/docker-ecr-project:latest

      - name: Push the Docker image to ECR
        run: |
          docker push 466670870088.dkr.ecr.us-east-1.amazonaws.com/docker-ecr-project:latest
